### PR TITLE
feat: remove registration form

### PR DESCRIPTION
**Pull request by momentiris**
**Ticket:** [#309](https://trello.com/c/Hq846iU8/309-remove-registration-screen)
**Intent:**
Remove registration form and the name entity from the app. Also fixes a bug where initial registration was considered finished even without choosing pds, after refresh.
**How to test (optional):**

### All of the following commands should pass.

- [x] `npm test`
- [x] `npm run lint`

### CODE REVIEW

**Comment by momentiris** [comment]
@lessp Yeah for sure, I'd say its for another card though.

**Comment by momentiris** [comment]
Node version seems to be correct. Removed it anyway.

**Comment by raduachim** [comment]
> Node version seems to be correct. Removed it anyway.

```
0.55s$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-09-25T13_26_34_633Z-debug.log
The command "npm ci" failed and exited with 1 during .
```

**Comment by momentiris** [comment]
added

**Pull request merged**
